{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "tekton-demo-deployment",
    "namespace": "tekton-pipelines"
  },
  "spec": {
    "minReadySeconds": 5,
    "replicas": 1,
    "revisionHistoryLimit": 10,
    "selector": {
      "matchLabels": {
        "app": "tekton-demo"
      }
    },
    "strategy": {
      "rollingUpdate": {
        "maxSurge": 2,
        "maxUnavailable": 1
      },
      "type": "RollingUpdate"
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "tekton-demo"
        }
      },
      "spec": {
        "containers": [
          {
            "image": "tonywu8293/tekton-demo:v1",
            "imagePullPolicy": "Always",
            "name": "tekton-demo",
            "ports": [
              {
                "containerPort": 8899
              }
            ]
          }
        ]
      }
    }
  }
}
